// This file was automatically generated by pnpm build:routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from "@/lib/routes";

const ROUTES_CONFIG = {
  "404": {},
  about: {},
  "code-of-conduct": {},
  events: {
    ":id": {
      assets: {
        ":__image.:__type": {},
        "_og-image": {},
        "_save-the-date-square": {},
        "_save-the-date": {},
        "_tickets-available-square": {},
        "_tickets-available": {},
        _utils: {},
        download: {},
      },
      attendee: {
        ":name": {
          ":__image.:__type": {},
          _social: {},
          _ticket: {},
          _utils: {},
        },
        _form: {},
      },
      pages: {
        ":subpageId": {},
      },
      partners: {
        ":partnerId": {
          assets: {
            ":__image.:__type": {},
            _square: {},
          },
        },
      },
      schedule: {},
      talks: {
        ":talkId": {
          assets: {
            ":__image.:__type": {},
            "_og-image": {},
            _square: {},
            _utils: {},
          },
        },
      },
    },
    locations: {
      ":countryId": {
        ":cityId": {},
      },
    },
    "rss.xml": {},
  },
  news: {
    "[...page]": {},
    article: {
      ":id": {
        assets: {
          ":__image.:__type": {},
          "_og-image": {},
        },
      },
    },
    "rss.xml": {},
  },
  people: {
    ":id": {},
  },
  podcasts: {
    ":id": {
      episodes: {
        ":episode": {
          assets: {
            ":__image.:__type": {},
            "_og-image": {},
          },
        },
      },
    },
    "rss.xml": {},
  },
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
