
// This file was automatically generated by @bearstudio/astro-typed-routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from '@bearstudio/astro-typed-routes';

const ROUTES_CONFIG = {
  "404": {},
  "about": {},
  "brand-assets": {},
  "call-for-papers": {
    "guidelines": {}
  },
  "code-of-conduct": {},
  "conferences": {
    ":page": {}
  },
  "events": {
    ":id": {
      "assets": {
        ":__image.:__type": {},
        "download": {}
      },
      "attendee": {
        ":name": {
          ":__image.:__type": {}
        }
      },
      "dashboard": {},
      "pages": {
        ":subpageId": {}
      },
      "partners": {
        ":partnerId": {
          "assets": {
            ":__image.:__type": {}
          }
        }
      },
      "schedule": {},
      "sponsors": {},
      "talks": {
        ":talkId": {
          "assets": {
            ":__image.:__type": {}
          }
        }
      }
    },
    ":id.html.md": {},
    "locations": {
      ":countryId": {
        ":cityId": {
          "assets": {
            ":__image.:__type": {}
          }
        },
        "assets": {
          ":__image.:__type": {}
        },
        "organizers": {
          "assets": {
            ":__image.:__type": {}
          }
        }
      }
    },
    "rss.xml": {},
    "types": {
      ":eventType": {}
    }
  },
  "fr": {
    "events": {
      "for-kids": {
        ":id": {
          "assets": {
            ":__image.:__type": {}
          },
          "schedule": {}
        }
      }
    }
  },
  "llms.txt": {},
  "news": {
    ":page": {},
    "article": {
      ":id": {
        "assets": {
          ":__image.:__type": {}
        }
      },
      ":id.html.md": {}
    },
    "rss.xml": {}
  },
  "people": {
    ":id": {
      "assets": {
        ":__image.:__type": {}
      }
    },
    ":id.html.md": {}
  },
  "podcasts": {
    ":id": {
      "episodes": {
        ":episode": {
          "assets": {
            ":__image.:__type": {}
          }
        },
        ":episodes.html.md": {}
      }
    },
    "rss.xml": {}
  },
  "resources": {
    "videos": {
      ":page": {}
    }
  }
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
