
// This file was automatically generated by @bearstudio/astro-typed-routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from '@bearstudio/astro-typed-routes';

const ROUTES_CONFIG = {
  "404": {},
  "about": {},
  "code-of-conduct": {},
  "conferences": {
    ":page": {}
  },
  "events": {
    ":id": {
      "assets": {
        ":__image.:__type": {},
        "_cfp-cover": {},
        "_og-image": {},
        "_qrcode-bg": {},
        "_qrcode": {},
        "_save-the-date-square": {},
        "_save-the-date": {},
        "_tickets-available-square": {},
        "_tickets-available": {},
        "_utils": {},
        "download": {}
      },
      "attendee": {
        ":name": {
          ":__image.:__type": {},
          "_social": {},
          "_ticket": {},
          "_utils": {}
        },
        "_form": {}
      },
      "dashboard": {},
      "pages": {
        ":subpageId": {}
      },
      "partners": {
        ":partnerId": {
          "assets": {
            ":__image.:__type": {},
            "_square": {}
          }
        }
      },
      "schedule": {},
      "sponsors": {},
      "talks": {
        ":talkId": {
          "assets": {
            ":__image.:__type": {},
            "_instagram": {},
            "_og-image": {},
            "_utils": {}
          }
        }
      }
    },
    ":id.html.md": {},
    "locations": {
      ":countryId": {
        ":cityId": {
          "assets": {
            ":__image.:__type": {},
            "_og-image": {},
            "_utils": {}
          }
        },
        "assets": {
          ":__image.:__type": {},
          "_og-image": {},
          "_utils": {}
        }
      }
    },
    "rss.xml": {}
  },
  "fr": {
    "events": {
      "for-kids": {
        ":id": {
          "assets": {
            ":__image.:__type": {},
            "_og-image": {},
            "_utils": {}
          },
          "schedule": {}
        }
      }
    }
  },
  "llms.txt": {},
  "news": {
    ":page": {},
    "article": {
      ":id": {
        "assets": {
          ":__image.:__type": {},
          "_og-image": {}
        }
      }
    },
    "rss.xml": {}
  },
  "people": {
    ":id": {
      "assets": {
        ":__image.:__type": {},
        "_og-image": {},
        "_utils": {}
      }
    },
    ":id.html.md": {}
  },
  "podcasts": {
    ":id": {
      "episodes": {
        ":episode": {
          "assets": {
            ":__image.:__type": {},
            "_og-image": {}
          }
        },
        ":episodes.html.md": {}
      }
    },
    "rss.xml": {}
  },
  "resources": {
    "videos": {
      ":page": {}
    }
  }
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
